// Embeds local .bnd files into samples.js so the file:// demo can offer a
// sample dropdown (file:// pages cannot fetch local files, so the text is
// baked in). samples.js is gitignored — machine-local data, like
// test-models/. Re-run this script to regenerate: node collect-samples.mjs
//
// Paths are this machine's EnergyPlus stashes; missing sources are skipped
// with a warning so the script degrades gracefully.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HOME = process.env.HOME;
const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const PROTO = `${HOME}/Documents/energyplus-files/prototype-testing/prototype-models/sim_output`;

const SOURCES = [
  ['1ZoneUncontrolled (no HVAC, 22.1)', `${REPO}/test-matrix/zone-uncontrolled-annual/eplusout.bnd`],
  ['Small Office PSZ (22.1)', `${REPO}/test-matrix/small-office-annual-sqlite/eplusout.bnd`],
  ['Large Office VAV + plant (22.1)', `${REPO}/test-models/large-office-multifreq/eplusout.bnd`],
  ['5ZoneAirCooled example (25.2)', `/tmp/eplus252-bnd/eplusout.bnd`],
  ['Hospital STD2022 (22.1, large)', `${PROTO}/ASHRAE901_Hospital_STD2022_ElPaso/eplusout.bnd`],
  ['Large Hotel STD2022 (22.1)', `${PROTO}/ASHRAE901_HotelLarge_STD2022_Atlanta/eplusout.bnd`],
  ['Apartment MidRise STD2022 (22.1)', `${PROTO}/ASHRAE901_ApartmentMidRise_STD2022_Denver/eplusout.bnd`],
  ['Small Hotel STD2022 (22.1)', `${PROTO}/ASHRAE901_HotelSmall_STD2022_Rochester/eplusout.bnd`]
];

const samples = [];
for (const [name, file] of SOURCES) {
  if (!fs.existsSync(file)) {
    console.warn(`skip (missing): ${name} — ${file}`);
    continue;
  }
  samples.push({ name, path: file, text: fs.readFileSync(file, 'utf8') });
  console.log(`embedded: ${name}`);
}

const out = path.join(path.dirname(fileURLToPath(import.meta.url)), 'samples.js');
fs.writeFileSync(
  out,
  `// Generated by collect-samples.mjs — do not edit, gitignored.\n` +
    `window.BND_SAMPLES = ${JSON.stringify(samples)};\n`
);
console.log(`wrote ${out} (${(fs.statSync(out).size / 1024 / 1024).toFixed(1)} MB, ${samples.length} samples)`);
